#Setup
```{r, error=FALSE, message=FALSE, warning=FALSE}

## Load the necessary libraries ################################################

library(readr)        # to import tabular data (e.g. csv)
library(dplyr)        # to manipulate (tabular) data
library(ggplot2)      # to visualize data
library(sf)           # to handle spatial vector data
library(terra)        # To handle raster data
library(lubridate)    # To handle dates and times
library(zoo)          # To handle moving window

## Import the downloaded csv ##################################################

wildschwein_BE <- read_delim("wildschwein_BE_2056.csv",",") 

wildschwein_BE <- st_as_sf(wildschwein_BE, coords = c("E", "N"), crs = 2056, remove = FALSE)

#set timelage
wildschwein_BE <- wildschwein_BE %>% 
  group_by(TierID) %>% 
  mutate(timelag = as.numeric(difftime(lead(DatetimeUTC),DatetimeUTC)))

summarise(wildschwein_BE, mean = mean(timelag, na.rm = T))
```
#Task 1: Getting an overview
```{r, error=FALSE, message=FALSE, warning=FALSE}
# How many individuals were tracked?
wildschwein_BE %>% group_by(TierID) %>% summarise(TierName = first(TierName))
# Three individual wildboars are tracked. Sabi, Rosa and Ruth

# For how long were the individual tracked? Are there gaps?
wildschwein_BE <- wildschwein_BE %>% group_by(TierID) %>% 
  mutate(firsttime= min(DatetimeUTC), lasttime=max(DatetimeUTC)) %>% 
  mutate(track_timediff = difftime(lasttime, firsttime))
wildschwein_BE %>% group_by(TierID) %>% 
  summarise(TierName = first(TierName), firsttime = first(firsttime),lasttime = first(lasttime), track_timediff = first(track_timediff))
ggplot(data = wildschwein_BE, aes(x = DatetimeUTC, y = TierID))+
  geom_line(color = "#00AFBB", size = 2)
# Animals are track from 2014 to 2015, where Sabi has 338.58 days, Rosa 234.67 days and Ruth 261.66 days.

ggplot(wildschwein_BE, aes(x=timelag, color=TierID)) +
  geom_histogram(fill="white", breaks=c(700, 890, 910, 1100, 3000,8000, 12000, 15000))
# Most tracks are performed under an interval of roughly 900 seconds and many are around this time, however a big amount of data has as well a tracking interval of around 3000 to 8000 seconds. The three individuals have similar time interval distribution
wildschwein_BE %>% filter(timelag > 1000) 
# There are 6254 entries which have more than 1000 seconds timelag and therefore a bigger time difference than the usual 900s
wildschwein_BE %>% group_by(TierID) %>% 
  summarise(actual_tracks=n(), expected_amount_of_tracks=as.integer(first(track_timediff)*24*60*60/900)) %>%
  mutate(percentage_tracked = actual_tracks * 100 / expected_amount_of_tracks)
# Under expectation of tracking every 15 minutes, the different animals have between 56% and 70% percent coverage of their tracks.

# Were all individuals tracked concurrently or sequentially?
# The animals were tracked over the same time periode, some over a longer and some over a shorter time.
# Which would indicate that they are tracked concurrently, but the data points are ordered sequentially-

# What is the temporal sampling interval between the locations?
wildschwein_BE %>%  mutate(time_lag_minute=as.integer(timelag/60)) %>% 
  group_by(TierID) %>% 
  summarise(mean_timelag = mean(timelag,na.rm = T), median_timelag_minute=median(time_lag_minute,na.rm = T))
# Usually every 15minutes = 900 second a new record is tracked. 
#But the mean timedifference of the animals is 1286, 1411, 1599 s) which is higher, therefore implicating that there are time gaps
ggplot(wildschwein_BE, aes(x=TierID, y=timelag, color=TierID)) +
  geom_boxplot()
# Many outliers of sampling for animal '018A'. But the sampling interval was probably set to 15minutes.


                    
```
#Task 2: Deriving movement parameters I: Speed
```{r, error=FALSE, message=FALSE, warning=FALSE}
wildschwein_BE <- wildschwein_BE %>% 
  group_by(TierID) %>% 
  mutate(steplength = as.integer(as.numeric((lead(N)-N))^2 + as.numeric(lead(E)-E)^2)^0.5)
wildschwein_BE <- wildschwein_BE %>% mutate(speed = steplength/timelag)

ggplot(wildschwein_BE, aes(x=TierID, y=speed, color=TierID)) +
  geom_boxplot() +
    labs(title="Speed of 3 wildboars",x="Animal ID", y = "Speed [m/s]")
# Unit is meter in seconds, since time difference has seconds as unit and the swiss coordinate system uses meter as unit.
```

#Task 3: Cross-scale movement analysis
```{r, error=FALSE, message=FALSE, warning=FALSE}
caro <- read_delim("caro60.csv",",") 
caro <- st_as_sf(caro, coords = c("E", "N"), crs = 2056, remove = FALSE)

caro3 <- caro %>% dplyr::slice(seq(from=1,to=length(caro$TierID), by=3))
caro6 <- caro %>% dplyr::slice(seq(from=1,to=length(caro$TierID), by=6))
caro9 <- caro %>% dplyr::slice(seq(from=1,to=length(caro$TierID), by=9))

caro <- caro %>% 
  mutate(timelag = as.numeric(difftime(lead(DatetimeUTC),DatetimeUTC)*60),
         steplength = as.integer(as.numeric((lead(N)-N))^2 + as.numeric(lead(E)-E)^2)^0.5) %>% 
  mutate(speed = steplength/timelag)
caro3 <- caro3 %>% 
  mutate(timelag = as.numeric(difftime(lead(DatetimeUTC),DatetimeUTC)*60),
         steplength = as.integer(as.numeric((lead(N)-N))^2 + as.numeric(lead(E)-E)^2)^0.5) %>% 
  mutate(speed = steplength/timelag)
caro6 <- caro6 %>% 
  mutate(timelag = as.numeric(difftime(lead(DatetimeUTC),DatetimeUTC)*60),
         steplength = as.integer(as.numeric((lead(N)-N))^2 + as.numeric(lead(E)-E)^2)^0.5) %>% 
  mutate(speed = steplength/timelag)
caro9 <- caro9 %>% 
  mutate(timelag = as.numeric(difftime(lead(DatetimeUTC),DatetimeUTC)*60),
         steplength = as.integer(as.numeric((lead(N)-N))^2 + as.numeric(lead(E)-E)^2)^0.5) %>% 
  mutate(speed = steplength/timelag)

dfcaro <- caro %>% mutate(group="0") %>% rbind(caro3 %>% mutate(group="3")) %>% rbind(caro6 %>% mutate(group="6")) %>% rbind(caro9 %>% mutate(group="9"))
ggplot(data=dfcaro, aes(x=DatetimeUTC, y=speed, group=group, colour=group)) +
  geom_line() +
    labs(title="Speed at various sample sizes",x="Time", y = "Speed [m/s]")

# Plot paths of different temporal sample
ggplot() +
  geom_path(data=caro9, aes(x=E, y=N, color="9 minute"), size=0.4, linetype=2) +
  geom_path(data=caro, aes(x=E, y=N, color="1 minute"), size=0.4, linetype=2) +
  labs(title="Path of different time sample intervals", x = "Easting", y = "Northing") +
    scale_color_discrete(name = "Sample interval")

ggplot() +
  geom_path(data=caro6, aes(x=E, y=N, color="6 minute"), color="blue", size=0.4, linetype=2) +
  geom_path(data=caro, aes(x=E, y=N, color="1 minute"), color="orange", size=0.4, linetype=2) +
  labs(title="Path of different time sample intervals (1 min in orange and 6 min in blue)", x = "Easting", y = "Northing")+
    scale_color_discrete(name = "Sample interval")

ggplot() +
  geom_path(data=caro3, aes(x=E, y=N, color="3 minute"), color="blue", size=0.4, linetype=2) +
  geom_path(data=caro, aes(x=E, y=N, color="1 minute"), color="orange", size=0.4, linetype=2) +
  labs(title="Path of different time sample intervals (1 min in orange and 3 min in blue)", x = "Easting", y = "Northing")+
    scale_color_discrete(name = "Sample interval")
```

#Task 4: Deriving movement parameters II: Rolling window functions
```{r, error=FALSE, message=FALSE, warning=FALSE}
# Calculate moving window speed
caro$speed3mov <- rollmean(caro$speed,k = 3,fill = NA,align = "left")
caro$speed5mov <- rollmean(caro$speed,k = 5,fill = NA,align = "left")
caro$speed7mov <- rollmean(caro$speed,k = 7,fill = NA,align = "left")

ggplot() +
  geom_line(data=caro, aes(x=DatetimeUTC, y=speed,color="1")) +
  geom_line(data=caro, aes(x=DatetimeUTC, y=speed3mov,color="3")) +
  geom_line(data=caro, aes(x=DatetimeUTC, y=speed5mov,color="5")) +
  geom_line(data=caro, aes(x=DatetimeUTC, y=speed7mov,color="7")) +
    labs(title="Speed with various moving windows",x="Time", y = "Speed [m/s]") +
    scale_color_discrete(name = "Moving window size", labels = c("original", "3", "5", "7"))
# Original data has more higher and more zero speed values, while the 7 size moving window has more smooth values.

ggplot(caro) +
  geom_boxplot(aes(x="1", y=speed, color='original'))+
  geom_boxplot(aes(x="3", y=speed3mov, color='moving window size 3'))+
  geom_boxplot(aes(x="5", y=speed5mov, color='moving window size 5'))+
  geom_boxplot(aes(x="7", y=speed7mov, color='moving window size 7'))+
  labs(title="Speed boxplot with various moving window sizes",x="Size of moving window", y = "Speed [m/s]")+ scale_color_discrete(name = "Moving window size")
# Mean stays the same, but higher speed outliers get less, the bigger the moving window size is.
```